# Generated by Django 2.2.11 on 2020-03-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20200306_1450'),
        ('events', '0002_auto_20200306_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='going',
            field=models.ManyToManyField(related_name='going', to='profiles.Profile', verbose_name='going'),
        ),
        migrations.AlterField(
            model_name='event',
            name='hosts',
            field=models.ManyToManyField(related_name='hosts', to='profiles.Profile', verbose_name='hosts'),
        ),
    ]
