# Generated by Django 2.2.11 on 2020-03-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('description', models.TextField(verbose_name='text')),
            ],
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('address', models.CharField(max_length=256, verbose_name='address')),
                ('type_of_venue', models.CharField(max_length=64, verbose_name='venue type')),
                ('sober', models.BooleanField(verbose_name='sober')),
                ('hidden_address', models.BooleanField(verbose_name='hidden address')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='contact email')),
                ('description', models.TextField(verbose_name='text')),
                ('slug', models.SlugField(verbose_name='slug')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='description')),
                ('slug', models.SlugField(verbose_name='slug')),
                ('followed_artists', models.ManyToManyField(related_name='followed_artists', to='profiles.Artist')),
                ('followed_venues', models.ManyToManyField(related_name='followed_venues', to='profiles.Venue')),
                ('friends', models.ManyToManyField(blank=True, to='profiles.Profile')),
                ('permitted_artists', models.ManyToManyField(related_name='permitted_artists', to='profiles.Artist')),
                ('permitted_venues', models.ManyToManyField(related_name='permitted_venues', to='profiles.Venue')),
            ],
        ),
    ]
