# Generated by Django 2.2.11 on 2020-03-06 13:52

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20200306_1349'),
    ]

    operations = [
    ]
