# Generated by Django 2.2.11 on 2020-03-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20200306_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='followed_artists',
            field=models.ManyToManyField(blank=True, related_name='followed_artists', to='profiles.Artist'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='followed_venues',
            field=models.ManyToManyField(blank=True, related_name='followed_venues', to='profiles.Venue'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='permitted_artists',
            field=models.ManyToManyField(blank=True, related_name='permitted_artists', to='profiles.Artist'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='permitted_venues',
            field=models.ManyToManyField(blank=True, related_name='permitted_venues', to='profiles.Venue'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='slug'),
        ),
    ]
